In [1]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [42]:
import numpy as np
import pandas as pd
import math as m
import yfinance as yf

Reading one year data of NIFTY 50 Index price from 03/01/2022 to 03/01/2023

In [43]:
df = pd.read_csv("/content/drive/MyDrive/NSEI_NIFTY_50.csv")
df.head(50)

Date          Open          High           Low         Close  \
0   2022-01-03  17387.150391  17646.650391  17383.300781  17625.699219   
1   2022-01-04  17681.400391  17827.599609  17593.550781  17805.250000   
2   2022-01-05  17820.099609  17944.699219  17748.849609  17925.250000   
3   2022-01-06  17768.500000  17797.949219  17655.550781  17745.900391   
4   2022-01-07  17797.599609  17905.000000  17704.550781  17812.699219   
5   2022-01-10  17913.300781  18017.449219  17879.150391  18003.300781   
6   2022-01-11  17997.750000  18081.250000  17964.400391  18055.750000   
7   2022-01-12  18170.400391  18227.949219  18128.800781  18212.349609   
8   2022-01-13  18257.000000  18272.250000  18163.800781  18257.800781   
9   2022-01-14  18185.000000  18286.949219  18119.650391  18255.750000   
10  2022-01-17  18235.650391  18321.550781  18228.750000  18308.099609   
11  2022-01-18  18337.199219  18350.949219  18085.900391  18113.050781   
12  2022-01-19  18129.199219  18129.199219  17884.900391  17938.400391   
13  2022-01-20  17921.000000  17943.699219  17648.449219  17757.000000   
14  2022-01-21  17613.699219  17707.599609  17485.849609  17617.150391   
15  2022-01-24  17575.150391  17599.400391  16997.849609  17149.099609   
16  2022-01-25  17001.550781  17309.150391  16836.800781  17277.949219   
17  2022-01-27  17062.000000  17182.500000  16866.750000  17110.150391   
18  2022-01-28  17208.300781  17373.500000  17077.099609  17101.949219   
19  2022-01-31  17301.050781  17410.000000  17264.150391  17339.849609   
20  2022-02-01  17529.449219  17622.400391  17244.550781  17576.849609   
21  2022-02-02  17706.199219  17794.599609  17674.800781  17780.000000   
22  2022-02-03  17767.750000  17781.150391  17511.150391  17560.199219   
23  2022-02-04  17590.199219  17617.800781  17462.550781  17516.300781   
24  2022-02-07  17456.300781  17536.750000  17119.400391  17213.599609   
25  2022-02-08  17279.849609  17306.449219  17043.650391  17266.750000   
26  2022-02-09  17370.099609  17477.150391  17339.000000  17463.800781   
27  2022-02-10  17554.099609  17639.449219  17427.150391  17605.849609   
28  2022-02-11  17451.000000  17454.750000  17303.000000  17374.750000   
29  2022-02-14  17076.150391  17099.500000  16809.650391  16842.800781   
30  2022-02-15  16933.250000  17375.000000  16839.250000  17352.449219   
31  2022-02-16  17408.449219  17490.599609  17257.699219  17322.199219   
32  2022-02-17  17396.550781  17442.900391  17235.849609  17304.599609   
33  2022-02-18  17236.050781  17380.800781  17219.199219  17276.300781   
34  2022-02-21  17192.250000  17351.050781  17070.699219  17206.650391   
35  2022-02-22  16847.949219  17148.550781  16843.800781  17092.199219   
36  2022-02-23  17194.500000  17220.699219  17027.849609  17063.250000   
37  2022-02-24  16548.900391  16705.250000  16203.250000  16247.950195   
38  2022-02-25  16515.650391  16748.800781  16478.300781  16658.400391   
39  2022-02-28  16481.599609  16815.900391  16356.299805  16793.900391   
40  2022-03-02  16593.099609  16678.500000  16478.650391  16605.949219   
41  2022-03-03  16723.199219  16768.949219  16442.949219  16498.050781   
42  2022-03-04  16339.450195  16456.000000  16133.799805  16245.349609   
43  2022-03-07  15867.950195  15944.599609  15711.450195  15863.150391   
44  2022-03-08  15747.750000  16028.750000  15671.450195  16013.450195   
45  2022-03-09  16078.000000  16418.050781  15990.000000  16345.349609   
46  2022-03-10  16757.099609  16757.300781  16447.900391  16594.900391   
47  2022-03-11  16528.800781  16694.400391  16470.900391  16630.449219   
48  2022-03-14  16633.699219  16887.949219  16606.500000  16871.300781   
49  2022-03-15  16900.650391  16927.750000  16555.000000  16663.000000   

       Adj Close  Volume  
0   17625.699219  200500  
1   17805.250000  247400  
2   17925.250000  251500  
3   17745.900391  236500  
4   17812.699219  239300  
5   18003.300781  232400  
6   18055.750000  220200  
7   18212.349609  2

VOLATILITY FUNCTION: This function is computed by calculating the percentage change of daily closing Prices and then computing the standard deviation of daily returns.

In [44]:
def volatility(df):
    df['volat'] = df['Adj Close'].pct_change()
    vol = df['volat'].std(ddof=0) * np.sqrt(252)
    return vol

In [45]:
volatility(df)

0.17256999226747566

In [46]:
df.head(50)

Date          Open          High           Low         Close  \
0   2022-01-03  17387.150391  17646.650391  17383.300781  17625.699219   
1   2022-01-04  17681.400391  17827.599609  17593.550781  17805.250000   
2   2022-01-05  17820.099609  17944.699219  17748.849609  17925.250000   
3   2022-01-06  17768.500000  17797.949219  17655.550781  17745.900391   
4   2022-01-07  17797.599609  17905.000000  17704.550781  17812.699219   
5   2022-01-10  17913.300781  18017.449219  17879.150391  18003.300781   
6   2022-01-11  17997.750000  18081.250000  17964.400391  18055.750000   
7   2022-01-12  18170.400391  18227.949219  18128.800781  18212.349609   
8   2022-01-13  18257.000000  18272.250000  18163.800781  18257.800781   
9   2022-01-14  18185.000000  18286.949219  18119.650391  18255.750000   
10  2022-01-17  18235.650391  18321.550781  18228.750000  18308.099609   
11  2022-01-18  18337.199219  18350.949219  18085.900391  18113.050781   
12  2022-01-19  18129.199219  18129.199219  17884.900391  17938.400391   
13  2022-01-20  17921.000000  17943.699219  17648.449219  17757.000000   
14  2022-01-21  17613.699219  17707.599609  17485.849609  17617.150391   
15  2022-01-24  17575.150391  17599.400391  16997.849609  17149.099609   
16  2022-01-25  17001.550781  17309.150391  16836.800781  17277.949219   
17  2022-01-27  17062.000000  17182.500000  16866.750000  17110.150391   
18  2022-01-28  17208.300781  17373.500000  17077.099609  17101.949219   
19  2022-01-31  17301.050781  17410.000000  17264.150391  17339.849609   
20  2022-02-01  17529.449219  17622.400391  17244.550781  17576.849609   
21  2022-02-02  17706.199219  17794.599609  17674.800781  17780.000000   
22  2022-02-03  17767.750000  17781.150391  17511.150391  17560.199219   
23  2022-02-04  17590.199219  17617.800781  17462.550781  17516.300781   
24  2022-02-07  17456.300781  17536.750000  17119.400391  17213.599609   
25  2022-02-08  17279.849609  17306.449219  17043.650391  17266.750000   
26  2022-02-09  17370.099609  17477.150391  17339.000000  17463.800781   
27  2022-02-10  17554.099609  17639.449219  17427.150391  17605.849609   
28  2022-02-11  17451.000000  17454.750000  17303.000000  17374.750000   
29  2022-02-14  17076.150391  17099.500000  16809.650391  16842.800781   
30  2022-02-15  16933.250000  17375.000000  16839.250000  17352.449219   
31  2022-02-16  17408.449219  17490.599609  17257.699219  17322.199219   
32  2022-02-17  17396.550781  17442.900391  17235.849609  17304.599609   
33  2022-02-18  17236.050781  17380.800781  17219.199219  17276.300781   
34  2022-02-21  17192.250000  17351.050781  17070.699219  17206.650391   
35  2022-02-22  16847.949219  17148.550781  16843.800781  17092.199219   
36  2022-02-23  17194.500000  17220.699219  17027.849609  17063.250000   
37  2022-02-24  16548.900391  16705.250000  16203.250000  16247.950195   
38  2022-02-25  16515.650391  16748.800781  16478.300781  16658.400391   
39  2022-02-28  16481.599609  16815.900391  16356.299805  16793.900391   
40  2022-03-02  16593.099609  16678.500000  16478.650391  16605.949219   
41  2022-03-03  16723.199219  16768.949219  16442.949219  16498.050781   
42  2022-03-04  16339.450195  16456.000000  16133.799805  16245.349609   
43  2022-03-07  15867.950195  15944.599609  15711.450195  15863.150391   
44  2022-03-08  15747.750000  16028.750000  15671.450195  16013.450195   
45  2022-03-09  16078.000000  16418.050781  15990.000000  16345.349609   
46  2022-03-10  16757.099609  16757.300781  16447.900391  16594.900391   
47  2022-03-11  16528.800781  16694.400391  16470.900391  16630.449219   
48  2022-03-14  16633.699219  16887.949219  16606.500000  16871.300781   
49  2022-03-15  16900.650391  16927.750000  16555.000000  16663.000000   

       Adj Close  Volume     volat  
0   17625.699219  200500       NaN  
1   17805.250000  247400  0.010187  
2   17925.250000  251500  0.006740  
3   17745.900391  236500 -0.010005  
4   17812.699219  239300  0.003764  
5   18003.300

MODEL ASSUMPTIONS AND VARIABLE NAMES:


*   Current stock price is: 𝑆
*   𝑇 is the Maturity time (taken as 200 days) of the Option, with 𝑁 number of periods(I calculate Option Price keeping N = 4,5,10)


*   d𝑡 is the time represented in each period
*   If the stock price goes up with a value U; such that: 𝑈 = 𝑒𝑥𝑝(𝜎 ∗ √𝛥𝑡) the new stock price value is: 𝑆u = 𝑆𝑜 ∗ 𝑈


*   If the stock price goes down by a value D; such that: 𝐷 = 𝑒𝑥𝑝(−𝜎 ∗ √𝛥𝑡) the new stock price value is: 𝑆𝑑 = 𝑆𝑜 ∗ D
*   The relationship between U and D is as follow: 𝑈 = 1/𝐷


*   The risk free interest rate, r, is taken as 6% p.a.










RISK NEUTRAL PROBABILITY

In [47]:
def RiskNeutralProbability(r,dt,v): # r: risk-free interest rate, dt = time duration of one period, v = volaitility
        u = np.exp(v*np.sqrt(dt))   # u: upfactor of spot price, d: down-factor of spot pticr
        d = 1/u
        rnp = (np.exp(r*dt)-d)/(u-d)
        return rnp

SPOT PRICE: I fetch the spot price of Yahoo Finance.

In [48]:
ticker = yf.Ticker('^NSEI')
df2 = ticker.history(period="1s")
S = df2["Close"]
S

Date
2023-07-14 00:00:00+05:30    19564.5
Name: Close, dtype: float64

BINOMIAL TREE OF SPOT PRICE OF STOCK

In [49]:
def spot_tree(n,T,S,v): # n: no. of periods, T: Maturity Time of the Option (in years), S: Spot Price , v: volatility
    dt = T/n
    u = np.exp(v*np.sqrt(dt))
    d = 1/u
    price_tree = np.zeros((n+1, n+1))
    for j in range(n+1):
        for i in range(j+1):
            price_tree[i,j] = S*m.pow(d,i) * m.pow(u,j-i)
    return price_tree

In [50]:
days_in_year = 365
n = 4
t = 200/days_in_year
v = volatility(df)
Tree1 = np.array(spot_tree(n,t,S,v))
n = 5
Tree2 = np.array(spot_tree(n,t,S,v))
n = 10
Tree3 = np.array(spot_tree(n,t,S,v))


print("Binomial Tree of Spot Prices when no. of periods = 4")
print(Tree1.astype(int))
print("Binomial Tree of Spot Prices when no. of periods = 5")
print(Tree2.astype(int))
print("Binomial Tree of Spot Prices when no. of periods = 10")
print(Tree3.astype(int))

Binomial Tree of Spot Prices when no. of periods = 4
[[19564.5  20854.87 22230.36 23696.56 25259.46]
 [    0.   18353.97 19564.5  20854.87 22230.36]
 [    0.       0.   17218.33 18353.97 19564.5 ]
 [    0.       0.       0.   16152.97 17218.33]
 [    0.       0.       0.       0.   15153.52]]
Binomial Tree of Spot Prices when no. of periods = 5
[[19564.5  20714.72 21932.57 23222.01 24587.26 26032.78]
 [    0.   18478.15 19564.5  20714.72 21932.57 23222.01]
 [    0.       0.   17452.11 18478.15 19564.5  20714.72]
 [    0.       0.       0.   16483.05 17452.11 18478.15]
 [    0.       0.       0.       0.   15567.8  16483.05]
 [    0.       0.       0.       0.       0.   14703.37]]
Binomial Tree of Spot Prices when no. of periods = 10
[[19564.5  20371.   21210.74 22085.11 22995.51 23943.45 24930.46 25958.15
  27028.22 28142.39 29302.49]
 [    0.   18789.93 19564.5  20371.   21210.74 22085.11 22995.51 23943.45
  24930.46 25958.15 27028.22]
 [    0.       0.   18046.03 18789.93 19564.5  2

BINOMIAL TREES FOR OPTION VALUES FOR CALL AND PUT OPTIONS

In [55]:
def Options_Tree(n, S, E, r, v, T, P_C):      # n: no. of periods, S: Spot Price, E: Exercise Price, r: risk-free rate
    dt = T/n                                 # T: Maturity Time of the Option (in years), v: volatility
    rnp = RiskNeutralProbability(r,dt,v)     # Put: if(Put=1) function computes Put Option tree, if(Put=0) function computes Call Option tree
    Spot_Tree = spot_tree(n,T,S,v)
    Option_Tree = np.zeros((n+1, n+1))

    for j in range(n+1, 0, -1):
        for i in range(j):
            if (P_C == 1):   #put option
                if(j == n+1):
                    Option_Tree[i,j-1] = max(E-Spot_Tree[i,j-1], 0)
                else:
                    Option_Tree[i,j-1] = m.exp(-r*dt)*(rnp*Option_Tree[i,j] + (1-rnp)*Option_Tree[i+1,j])
            if (P_C == 0):   #call option
                if (j == n + 1):
                    Option_Tree[i,j-1] = max(Spot_Tree[i,j-1]-E, 0)
                else:
                    Option_Tree[i,j-1] = m.exp(-r*dt) * (rnp*Option_Tree[i,j] + (1-rnp)*Option_Tree[i+1,j])
    return [Spot_Tree,Option_Tree]

In [62]:
N = 200 # Maturity Time of Option in Days
days_in_year = 365
E = S.item() #Taking Exerice Price equal to spot price
r = 0.06
T = N/days_in_year
v = volatility(df)
n = 4
P_C = 0
Spot_Tree,Call_Option_Tree = Options_Tree(n,S,E,r,v,T,P_C)
P_C = 1
Spot_Tree,Put_Option_Tree = Options_Tree(n,S,E,r,v,T,P_C)
print('No. of Periods: 4')
print('Spot Price Tree:\n',np.matrix(Spot_Tree.astype(int)))
print('Call Option Tree:\n',np.matrix(Call_Option_Tree.astype(int)))
print('Put Option Tree:\n',np.matrix(Put_Option_Tree.astype(int)))
print('\n')
n = 10
P_C = 0
Spot_Tree,Call_Option_Tree = Options_Tree(n,S,E,r,v,T,P_C)
P_C = 1
Spot_Tree,Put_Option_Tree = Options_Tree(n,S,E,r,v,T,P_C)
print('No. of Periods: 10')
print('Spot Price Tree:\n',np.matrix(Spot_Tree.astype(int)))
print('Call Option Tree:\n',np.matrix(Call_Option_Tree.astype(int)))
print('Put Option Tree:\n',np.matrix(Put_Option_Tree.astype(int)))

No. of Periods: 4
Spot Price Tree:
 [[19564 20854 22230 23696 25259]
 [    0 18353 19564 20854 22230]
 [    0     0 17218 18353 19564]
 [    0     0     0 16152 17218]
 [    0     0     0     0 15153]]
Call Option Tree:
 [[1268 1977 2984 4292 5694]
 [   0  429  789 1450 2665]
 [   0    0    0    0    0]
 [   0    0    0    0    0]
 [   0    0    0    0    0]]
Put Option Tree:
 [[ 635  210    0    0    0]
 [   0 1163  470    0    0]
 [   0    0 2027 1050    0]
 [   0    0    0 3251 2346]
 [   0    0    0    0 4410]]


No. of Periods: 10
Spot Price Tree:
 [[19564 20370 21210 22085 22995 23943 24930 25958 27028 28142 29302]
 [    0 18789 19564 20370 21210 22085 22995 23943 24930 25958 27028]
 [    0     0 18046 18789 19564 20370 21210 22085 22995 23943 24930]
 [    0     0     0 17331 18046 18789 19564 20370 21210 22085 22995]
 [    0     0     0     0 16645 17331 18046 18789 19564 20370 21210]
 [    0     0     0     0     0 15986 16645 17331 18046 18789 19564]
 [    0     0     0     0 